## =========================================================================
## =========================================================================

all: main

main: main.cxx
	g++ -std=c++17 create_sorting_data.cxx -o create_sorting_data

clean:
	rm -f main *.aux *.log *.pdf

# eof - makefile
